BROKER_URL = 'redis://localhost:6379/0'#'amqp://'
CELERY_RESULT_BACKEND = "redis://localhost/0"#'amqp://'

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERYD_HIJACK_ROOT_LOGGER=False
CELERY_JOB_TIMEOUT = 10
CELERY_TASK_RESULT_EXPIRES=3600